print()
print('===== Exercício 006 =====')
print()
n = int(input('Insira um número: '))
print('Ok, o número que você inseriu é {}\nSeu dobro é {}\nSeu triplo é {}\nE sua raiz quadrada é {}.'.format(n, (n*2), (n*3), pow(n, (1/2))))
print()
print('FIM')
