print()
print('===== Exercício 004 =====')
print()
a = input('Digite algo (qualquer coisa) em seu teclado: ')
print('* O tipo primitivo desse valor é:', type(a),'.')
print('* Só tem letras maiusculas?', a.isupper())
print('* Só tem letras?', a.isalpha())
print('* Só tem caracteries Alfanúmericos?', a.isalnum())
print('* É númerico?', a.isnumeric())
print('* É/São caracterie(s) da tabele ASCII?', a.isascii())
print('* É décimal?', a.isdecimal())
print('* É digito?', a.isdigit())
print('* É identificador?', a.isidentifier())
print('* É minúsculo?', a.islower())
print('* É algo imprimivél?', a.isprintable())
print('* Só tem espaços?', a.isspace())
print('* Está capitalizada (Maiúscula e Minúscula)?', a.istitle())
print('* Qual o método de subclasse?', a.__init_subclass__())
print()
print('FIM')
