print()
print('===== Exercício 005 =====')
print()
print('MODO 01')
print()
v = int(input('Insira um valor de entrada: '))
a = v - 1
s = v + 1
print('Obrigado, seu número inserido foi {}, seu antecessor é {}, e o seu sucessor é {}.'.format(v, (v-1), (v+1)))
print()
print('FIM 1')
print('........................................')
print('MODO 02')
print()
v = int(input('Insira um valor de entrada: '))
print('Obrigado, seu número inserido foi {}, seu antecessor é {}, e o seu sucessor é {}.'.format(v, (v-1), v+1))
print()
print('FIM 2')
